name: Build Sample for Android

on: [push, pull_request]

jobs:
  apk:
    name: Apk Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the APK
        run: |
              cd android-project/
              ./gradlew assembleDebug

      - name: Upload the APK
        uses: actions/upload-artifact@v4
        with: 
          name: app-debug.apk
          path: android-project/app/build/outputs/apk/debug/app-debug.apk
