name: Build Sample
on: [push, pull_request]

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              arch: [x64, ARM64]
              target: [Windows]

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Configure
            run: | 
                mkdir build && cd build
                cmake -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }} ..
          - name: Build
            run: cmake --build build --target sdl-template --config Release
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: sdl-template-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/Release/*.exe
                    build/Release/*.dll

    build-mac:
        name: Build for Apple
        runs-on: macos-14
        strategy:
          fail-fast: false
          matrix:
              target: ['Darwin']

        steps:
          - uses: actions/checkout@v4
            with:
                submodules: true
          - name: Setup Xcode version
            uses: maxim-lobanov/setup-xcode@v1.6.0
            with:
                xcode-version: "15.3"
          - name: Configure
            run: | 
                mkdir -p build 
                mkdir -p build/mac
                cd build/mac
                pwd
                cmake -G "Xcode" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DSDL_STATIC=ON -DSDL_SHARED=OFF -S ../.. -B ./build
          - name: Build
            run: |
              pwd
              ls
              cd build
              ls
              cmake --build ./build --target install --config Release
          # - name: Build
          #   run: |
          #     cmake --build . --target install --config Release
          #     rm -rf ./sdl-template.app/Contents/MacOS/assets || true
          #     cp -R ../assets ./sdl-template.app/Contents/MacOS/assets

          # - name: Create DMG
          #   run: | 
          #       cd build
          #       hdiutil create -size 2g -srcfolder install -volname sdl-template-apple-${{ matrix.target }} sdl-template-apple-${{ matrix.target }}.dmg
          - name: Create DMG
            run: | 
                cpack -G DragNDrop -C Release
          - name: Upload Build
            uses: actions/upload-artifact@v4
            with: 
                name: sdl-template-apple-${{ matrix.target }}
                path: |
                  ./*.dmg
